navikt/familie-ba-soknad

src/App.tsx, src/context/AppContext.ts
Interceptoren ble aldri kalt da den lå i `AppContext.tsx`, og ble derfor flyttet til `App.tsx` slik at den håndterer 401-feil.
=> bugfix: flytt interceptor-kall til App.tsx

server.js, src/Miljø.ts
Håndterer routingproblem som oppstod under redirect.
I tillegg fikser det feilen ved å bruke "../noe" på localhost:9000 etter `yarn build_and_serve`
=> bugfix: håndter routing i prod og test

.idea/runConfigurations/_template__of_JavaScriptTestRunnerJest.xml
Fikse å kjøre tester fra intellij-shortcuts. Bruker `react-scripts test` by default, trenger å endre til å bruke jest
Det er ikke mulig å teste ide-config
Checkout branch og sjekk at jest-templaten i run configurations har endret seg
=> (fix) Få intellij til å kjøre frontend-tester med jest

package.json, yarn.lock
Oppgradere html-webpack-plugin til versjon 5. Nr. 4 ga en deprecated warning i terminalen når man startet serveren.
Nei
Ingenting å teste
Alt i ett
=> Oppgrader html-webpack-plugin fra 4 til 5 som skapte deprecated warning

src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx
Man kunne i nå alt i modal når man hadde valgt 200% og "very large" tekst størrelse. Det var pga, min høyden som gjorde at man ikke fikk scrollet helt ned/opp.
nei
nei/niet/nay/no
Alt i ett
=> Ta bort min-høyde som gjør at får se alt i modalen ved scroll

src/webpack/webpack.common.config.js, src/webpack/webpack.development.config.js, src/webpack/webpack.production.config.js
Sette eksplisitte paths til kompilerte js-chunks i preprod og prod slik at man ikke bare får index.html hvis man navigerer direkte til en subpath.
Nei
Det går sikkert an å skrive tester for webpack, men jeg veit ikke hvordan
Alt i ett
=> (fix) Direkte navigering i prod

src/frontend/components/Felleskomponenter/SkjemaCheckbox/SkjemaCheckbox.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx
At advarsel ikke vises når man huker av for at barn ikke har fått fødselsnummer
Nei
Alt i ett
=> (hotfix) Fiks at advarsel om at man må ha fnr vises

src/backend/dekorator.ts, src/backend/server.ts, src/webpack/webpack.common.config.js, src/webpack/webpack.development.config.js
Fikse at vi har dobbel `/` i svg img-paths både lokalt og i prod, fikse asset loading lokalt, fikse at man ikke kan laste manifest.json og sånn lokalt fordi dev-mode og prod-mode hadde ulik output-mode.
Før rendret vi kun index.html som fallback, nå rendrer vi den først hvis request path er `/`. Siden express-handlere kalles i sekvens lar det oss forenkle devloaderen slik at den funker mer likt prod-mode :tada: 
Usikker på om vi trenger tester for tynn backend, men begynner å tro at vi kanskje burde ha det.
Alt i ett
=> (fix) Asset loading lokalt, forenkla devloader++

package.json, src/frontend/Miljø.ts, src/frontend/components/Felleskomponenter/BlokkerTilbakeKnappModal/BlokkerTilbakeKnappModal.test.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/HvilkeBarnCheckboxGruppe.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useBarnCheckboxFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.test.ts, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.ts, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummeringsbolk.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/useLeggTilBarn.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.tsx, src/frontend/components/SøknadsSteg/VelgBarn/useVelgBarn.tsx, src/frontend/context/AppContext.ts, src/frontend/context/RoutesContext.tsx, src/frontend/typer/person.ts, src/frontend/utils/person.ts, src/frontend/utils/testing.tsx, yarn.lock
Endre til å bruke generert uid for barn istedenfor fnr/dnr til å identifisere barn i frontend
Har endret funksjonalitet og søknadskontrakt slik at barn blir tildelt uid så snart vi mottar barnet fra backend. Dette for å unngå problematikk med at barn fikk nye id'er hver render/refresh slik at man fortsatt kan bruke mellomlagring.
Alt i ett
=> (fix) Endre til å ikke bruke fnr/dnr som id for barn

src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.test.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx
rendrer ikke infotekst og har-sendt-inn-før-checkbox for ANNEN_DOKUMENTASJON
Fjerner infotekst og checkbox for ANNEN_DOKUMENTASJON
nei
Før
Etter
=> fix vedlegg ANNEN_DOKUMENTASJON visning

src/backend/feature-toggles.ts, src/backend/server.ts
Flytt static-handler før feature-toggle-middleware, slik at middlewaren
ikke trenger å vite hvilke filtyper som må slippes igjennom. Legg til
environment-variabel som kan force kill-switch behavior for utvikling.
Løser at css ikke kan lastes når disable kill-switchen er på.
Løser også at man måtte endre kode for å teste disabled-appen lokalt uten å toggle kill-switchen i unleash.
Nei
Har ikke tester for backend
Alt i ett
=> (fix) Tryggere forenklet feature-toggle middleware

package.json
Sette BASE_PATH når man kjører start:dev slik at både ordinær og utvidet kan testes lokalt uten kodeendring
Dette krasjer litt med docker-tingene og må kanskje byttes ut med en distribuert intellij runconfiguration senere.
Ingen kodeendring
Alt i ett
=> (chore) Endre start:dev til å ha en base-path for å utvikle på utvidet

src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx
Fikse en bug der andre forelder ikke blir nullstilt dersom man velger ikke fosterbarn -> fyller ut forelder -> går til oppsummering -> går tilbake -> velger at barn er fosterbarn -> trykker seg videre
=> Nullstill andre forelder dersom man huker av at barnet er fosterbarn

docker-compose.yml, src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx
Bruk "ikke oppgitt" istedenfor "ukjent" i PDF for søknadsperiode. Har også bumpet commit-hashes i docker-compose.yml
Nei
Egen branch for testing av denne funksjonen
Alt i ett
=> (fix) Bruk 'Ikke oppgitt' for svar på søknadsperiode når ukjent

src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/OmDeg/useDatovelgerFeltMedJaNeiAvhengighet.ts, src/frontend/typer/person.ts, src/frontend/utils/dato.tsx, src/frontend/utils/person.ts
Endrer slik at søker-fra-dato og søker-til-dato blir satt til UKJENT hvis de ikke er synlige eller hvis til-dato ikke fylles ut, slik at useSendInnSkjema kan fange dem opp og sette riktig ukjent-verdi i innsending.
Kommer tilhørende PR i dokgen.
=> (fix) Sett fra-til-felter til UKJENT istedenfor blank string

docker-compose.yml, src/backend/server.ts, src/webpack/webpack.production.config.ts
Gjør det mulig å bruke killswtichene igjen, fikse caching av css mellom deploys
Ved å kjøre static-handleren før feature-toggle handleren lar vi browsere laste ned js/css-filer uavhengig av killswitch status, som gjør at vi ikke cacher index.html som svar på js/css-filer som hang igjen når vi skrudde switchene av ighen
Nei
Anser unødvendig mye arbeid
Alt i ett
=> (hotfix) Fix killswitches og cache-problemer

build_n_deploy/naiserator/naiserator_dev.yaml, build_n_deploy/naiserator/naiserator_prod.yaml, docker-compose.yml, dockerstuff/soknad-api/Dockerfile, dockerstuff/soknad-api/gitdiff, src/backend/environment.ts
Nå når `familie-ba-soknad-api` har fått nytt navn må alle referanser til applikasjonen endres til det nye navnet: `familie-baks-soknad-api`.
Denne kan ikke merges før ny app `familie-baks-soknad-api` har fått tilgang til `pdl` i prod.
=> Endret alle forekomster av familie-ba-soknad-api til familie-baks-soknad-api

src/frontend/utils/dato.tsx
Validering av datofeltet sjekket ikke at formatet på datoen var riktig. Legger inn korrekt parsing av string til dato slik at dato blir invalid dersom formatet ikke er riktig.
=> Sørger for at vi validerer at dato er på rett format for Backend

package.json, yarn.lock
Etter at vi oppgraderte til v5 av aksel, så har vi fått warnings på at familie-form-elements ikke håndterte v5 (+ familie-språkvelger sin dependency til familie-form-elements)
Nei
Bare oppgradering av dependency
Samme hvor du starter
Det visuelle har ikke endret seg
=> Chore/oppgrader familie-form-elements

.github/dependabot.yml
Lager grupperingsregler for Dependabot, slik som vi har for BA-sak og KS-sak. Dette gjør at dependabot ser på grupperte avhengigheter som en helhet, og lager felles PR for disse. 
Se tilsvarende konfigurasjon i ks-sak: https://github.com/navikt/familie-ks-sak-frontend/blob/main/.github/dependabot.yml
=> Lag grupperingsregler for dependabot

src/frontend/components/Felleskomponenter/FamilieAlert/FamilieAlert.tsx, src/frontend/components/SøknadsSteg/Forside/BekreftelseOgStartSoknad.tsx, src/frontend/components/SøknadsSteg/Forside/Forside.tsx
Endrer layout og tekster på forsiden, slik at den kan brukes felles for begge søknadene
Vi flyttet "Vi stoler på deg" inn i bekreftelsesboksen, både med og uten toggle. Utover dette skal det kun være endringer med toggle.
TOGGLE AV:
TOGGLE PÅ:
=> Legge inn/endre tekster for felles forside

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_pr.yaml
1. Legg til action for å _kun bygge_ ved commits til utviklingsbrancher
2. Skrur av autodeploy til dev ved alle commits til utviklingsbrancher
=> Chore: skru av autodeploy til dev

src/frontend/components/Felleskomponenter/Sanity/TekstBlock.tsx, src/frontend/utils/sanity.ts
Del av denne: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18565
Legger til støtte for ny implementasjon av flettefelt. I en mellomfase vil koden nå støtte både gammel og ny variant, frem til alt gammelt er slettet fra Sanity. Tanken er at BA-tekster ikke skal bruke de gamle flettefeltene, men det er greit å beholde den gamle implementasjonen enn så lenge, just in case. 
Kommer til å legge til tilsvarende i ks-soknad, slik at denne også støtter begge type flettefelter i en mellomperiode.
Har testet manuelt at det funker …
=> Feat: støtte ny implementasjon av flettefelt

.github/workflows/build_pr.yaml
Vi kjører tester og bygg på PR-nivå, og bygger fra main mot prod i egen action. Trenger ikke å gjøre det også i denne action. Men enten så har github endret syntaks for å ignorere branches eller så har jeg rett og slett "visst feil"! 😮
=> Korriger syntaks for å ignorere main-branch

src/frontend/components/SøknadsSteg/Forside/BekreftelseOgStartSoknad.tsx, src/frontend/components/SøknadsSteg/Forside/Forside.tsx, src/frontend/context/AppContext.ts, src/frontend/typer/sanity/sanity.ts, src/frontend/typer/sanity/tekstInnhold.ts, src/frontend/utils/sanity.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18565
Flytter over resten av tekstene som ligger bak KOMBINER_SØKNAD-toggle til Sanity. 
Nei. Kommer til å teste i preprod før merge, med både toggle av og på.
Tester manuelt at ting funker som det skal
Alt i ett er sikkert like greit, har vært litt frem og tilbake
=> Legg inn sanity-tekster på forsiden

src/frontend/components/Felleskomponenter/Banner/Banner.tsx
Tidligere hadde vi ulik heading avhengig av om man søkte utvidet eller ordinær. Nå får man samme heading uansett.
=> Bruker samme heading på alle sider uavhengig av søknadstypen

src/frontend/components/SøknadsSteg/DinLivssituasjon/DinLivssituasjon.test.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/DinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/LeggTilSamboerModal.test.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/NåværendeSamboer.test.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/TidligereSamboere.test.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/useDinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/DinLivssituasjonOppsummering.tsx, src/frontend/context/AppContext.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata1.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata2.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata3.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata4.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata5.ts, src/frontend/typer/person.ts, src/frontend/typer/søknad.ts, src/frontend/utils/mappingTilKontrakt/søknadV8.ts, src/frontend/utils/testing.tsx, src/shared-utils/modellversjon.ts
Fjerne spørsmål om samboer dersom man søker ordinær barnetrygd.
Har fjernet spørsmålet fra steget "Livssituasjonen din" og satt skjemafeltet til "skjult" dersom søknadstype er ordinær for å hindre validering på feltet i skjema-hooket.
Før:
Etter:
=> Fjern spørsmål om samboer i søknad om ordinær barnetrygd

src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx, src/frontend/typer/søknad.ts
Favro: [vi har kombinert søknad for utvidet og ordinær](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18565)
Tidligere la vi til dokumentasjonsbeskrivelse for utvidet i dokumentasjonsbehovet dersom `/utvidet` var i URLen. Men nå som vi har kombinert søknads-URL-ene har vi ikke lengre tilgang på søknadstype der vi oppretter initielt objekt for dokumentasjonsbehov. Etter å ha sett litt på logikken ser vi at vi senere i flyten, i `LastOppVedlegg.tsx`, der vi rendrer ut dokumentasjonsbehovene, filtrerer vekk dokumentasjon for utvidet dersom brukeren søker ordinær. Dermed kan vi trygt legge til dokumentasjonsbehovet for utvidet i det initielle …
=> Legg alltid til dokumentasjonsbeskrivelse for utvidet, den filtreres bort ved behov

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.test.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18710
- Bytter ut Alert komponent som tilleggsinfo for JaNeiSpm med tekstId for å fjerne info-ikon forran hjelpetekst.
- Jeg har ikke skrevet tester, men endrer tester for `omDeg.test.tsx` ettersom 'alertstripe' ikke lengre tas i bruk.
- Gjør applikasjonen og se på hjelpetekstene under spørsmål i "Om deg" og "Barna dine".
=> Fjerner alle info tegn ved hjelpetekster i spørsmål

src/frontend/Theme.ts
Fjerner custom CSS som tukler med CSSen til dekoratørens footer. 
Fiks på det visuelle uttrykket som vises fra dekoratøren krever ikke tester.
Desktop:
Mobil:
Desktop:
Mobil:
=> Fjerner custom CSS for dekoratøren sin footer, det setter feil bredde på footeren

src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/context/Steg.test.tsx, src/frontend/context/StegContext.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21058
- Bytter ut Stepper komponenten med FormProgress
- Ingen nye tester er skrevet, men testen for hvor stor listen over hvor mange formProgressSteps (tidligere stepperObjekter) endres ettersom Kvittering ikke skal være del av FormProgress i følge Aksel: https://aksel.nav.no/komponenter/core/formprogress#:~:text=mer%20skreddersydd%20framdriftsindikator.-,Hvilke%20steg%20skal%20v%C3%A6re%20med%3F,-Introside%20og%20kvitteringsside
- Gå gjennom søknaden og se at FormProgress viser steg på riktig måte.
=> Bytter fra Stepper til FormProgress for skjema-steg

src/frontend/context/SanityContext.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21906
- Fjerner filtrering av ytelse når tekster hentes fra Sanity slik at alle tekster hentes, uavhengig om hva slags avhukinger som er gjort.
=> Fjerner filtrering av ytelse når tekster hentes fra Sanity

src/frontend/components/Kontoinformasjon/Kontoinformasjon.tsx, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/components/SøknadsSteg/Kvittering/innholdTyper.ts, src/frontend/context/AppContext.ts, src/frontend/typer/feature-toggles.ts, src/frontend/typer/kontoinformasjon.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-20794
Henter og viser kontonummer fra baks-soknad-api (som igjen henter det fra Kontoregisteret Person).
Har lagt fetchingen der jeg ser mye annen fetching skjer, i `AppContext`. Si ifra hvis dette blir feil sted å legge det.
Skal skrive tester etter hvert, men siden denne oppgaven har ligget så lenge så prioriterer jeg nå å få ut en PR på det.
Alt i ett
Happy case - med kontonummer:
Uten kontonummer:
Dette slettes - før ble det vist informasjon om kontonummer når det var en EØS-søknad:
=> Henter og viser kontoinformasjon

src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/Filopplaster.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/useFilopplaster.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/innholdTyper.ts
Favro: [NAV-22223](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22223)
Begrenser antall opplastede vedlegg til 25.
Dersom man forsøker å laste opp flere enn 25 vedlegg totalt i søknaden viser vi en feilmelding til bruker.
Bytter også ut alle lokale språktekster relatert til feilmeldinger ved opplasting med tekster fra Sanity.
=> Begrenser antall opplastede vedlegg til 25

src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx
Favro: NAV-22388
Dersom man søker utvidet barnetrygd for barn over 16 år skal vi ikke be om meklingsattest. Kun for barn under 16 år. 
For barn med ubestemt fødselsdato i PDL og barn som søker selv har lagt til manuelt i søknaden, beregner vi ikke alder og vil fremdeles be om meklingsattest.
Fint om dere ser over om jeg har vært for naiv i løsningen min 😇 
Har testet manuelt
Gitt barn født 01.01.08 (16 år) ber vi ikke om meklingsattest hverken i infoboks eller på dokumentasjonssiden:
=> Ikke be om meklingsattest for barn over 16

src/frontend/components/Felleskomponenter/SkjemaCheckbox/SkjemaCheckboxForSanity.tsx, src/frontend/components/Felleskomponenter/SkjemaFeltInput/SkjemaFeltInputForSanity.tsx, src/frontend/components/Felleskomponenter/SøkerMåBrukePDF.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/BarnekortInfo.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.tsx, src/frontend/components/SøknadsSteg/VelgBarn/innholdTyper.ts, src/frontend/typer/sanity/modaler/leggTilBarn.ts, src/frontend/typer/sanity/sanity.ts, src/frontend/typer/sanity/tekstInnhold.ts, src/frontend/utils/sanity.ts
Favro: [NAV-22907](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-22907)
- Bytter fra bruk av lokale tekster til Sanity i "Velg barn" steget.
- Endrer tester til å ta i bruk testid fremfor å søke etter tekster.
- Legger til Sanity komponenter for `SkjemaCheckboxForSanity` `SkjemaFeltInputForSanity`.
- Forbedrer `SøkerMåBrukePdf` komponenten til å ha likt tekstinnhold som i KS og endrer bruk av `Alert`.
- Tester er endret, men ingen nye er lagt til ettersom ny funksjonalitet ikke er lagt til.
- Alt i ett
- Hovedsaklig ikke visuelle endringer ettersom oppgaven går ut på å endre hvordan tekster hentes.
=> Legger til sanity tekster i velg barn

src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.test.tsx, src/frontend/hooks/useJaNeiSpmFelt.tsx
- Endrer spørsmål-feilmeldinger til å kunne ta i bruk tekster fra Sanity (likt som i KS).
- Legger til Sanity feilmeldinger for spørsmål i "Om deg" steget.
- Ikke nødvendig ut fra hva jeg kan se.
- Tester er ikke fjernet eller lagt til, men `Oppsummering.test.tsx` > `stopper fra å gå videre hvis søknaden har mangler` er endret ettersom den tidligere var basert på tekstinnhold som ikke er tilgjengelig fra Sanity (ettersom Sanity-teskter mockes).
- Alt i ett
=> Endrer spørsmål-feilmeldinger til å kunne ta i bruk tekster fra Sanity

src/shared-utils/Miljø.ts
Vi får en rekke CORS issues dersom man forsøker å bruke ansatt-url. Dette er fordi vi har satt opp koden til å bruke intern-url ved alle kall mot backend-del av frontend. Backend-del av frontend er satt opp til å ikke godta slike kall fra andre enn "self". Altså må url man står på samsvare med url man bruker mot backend-del av frontend:
* Står man på `*ansatt.dev.nav.no` må man gå mot backend-del av frontend med urlen `*ansatt.dev.nav.no`
* Står man på `*intern.dev.nav.no` må man gå mot backend-del av frontend med urlen `*intern.dev.nav.no`
Fikser dette ved å sjekke om man står på en ansatt-url når vi bestemmer urler i `Miljø.ts`.
=> Fikser CORS problem når vi har 2 ingresser i dev-gcp

package.json, yarn.lock
Samme som vi har gjort [i andre repoer](https://github.com/navikt/familie-ba-sak-frontend/pull/3404), vi må fikse `lint-staged` for å få lov til å bumpe micromatch, som har et sikkerhetshull.
Trenger ikke tester, jeg har testet manuelt at det fungerer å stage og committe.
=> Bumper lint-staged for å kunne fikse sikkerhetsproblem i micromatch

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummeringsbolk.tsx, src/frontend/components/SøknadsSteg/Oppsummering/innholdTyper.ts
Favro: [NAV-23323](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23323)
- Endrer Oppsummeringsbolk til å kunne bruke Sanity tekster for tittel (+ flettefeltverdier).
- Bytter til bruk av Sanity tekster for OmDegOppsummering.
- Alt i ett.
- Ingen visuelle endringer.
=> Bytter til bruk av Sanity tekster for OmDegOppsummering

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/DinLivssituasjonOppsummering.tsx
Favro: [NAV-23357](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23357)
- Bytter til bruk av Sanity tekster for `DinLivssituasjonOppsummering`.
- Tekster brukt i `SamboerOppsummering` tar fortsatt i bruk lokale tekster ettersom `SamboerSkjema` fremdeles også bruker lokale tekster. (`SamboerOppsummering` er en oppsummering av resultater fra `SamboerSkjema`)
- Alt i ett.
- Ingen visuelle endringer.
=> Bytter til bruk av Sanity tekster for DinLivssituasjonOppsummering

package.json, yarn.lock
`react-cookie` har en dependency til `universal-cookie` som igjen har en dependency på `cookie`. Den gamle versjonen av `universal-cookie` dependet på en versjon av `cookie` som har et sikkerhetshull (versjon under `0.7.0`). Bumper react-cookie i samme slengen.
Ikke noe spesielt
Ikke relevant
=> Bumper react-cookie (og universal-cookie under der igjen) for å fikse sikkerhetshull

package.json, yarn.lock
Dependencien `nodemon` ble lagt til i commit [8348943](https://github.com/navikt/familie-ba-soknad/commit/8348943455f4673390204840a0eac891f58fc61e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R13) men ikke fjernet igjen når vi ikke lenger brukte scriptet `ts:server`. Jeg finner ingen annen bruk av denne, derfor sletter jeg den.
Ingen bekymringer. Så vidt jeg ser er det ingen bruk av `nodemon`, ingen dependencies som trenger `nodemon` ei heller noen peerDependencies som trenger `nodemon`. All good!
Ikke relevant
=> Fjerner dependencien nodemon som ikke i bruk lenger

src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx
Favro: [NAV-24095](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24095)
Samme oppgave er gjort i KS: https://github.com/navikt/familie-ks-soknad/pull/751
- Endrer `allNødvendigDokumentasjonErLastetOpp` til å også sjekke for antall opplastede vedlegg, ikke bare om dokumentasjon er sendt inn fra før.
- Endrer variabel navn fra `alleRelevanteVedleggErSendtInn` til `allNødvendigDokumentasjonErLastetOpp`.
- Alt i ett.
Før ble varsel vist, selv når all dokumentasjon var gitt.
Etter blir varsel kun vist når ikke all dokumentasjon er gitt.
=> Fikser visning av alert for allNødvendigDokumentasjonErLastetOpp

package.json, src/backend/middlewares/erklaering-interceptor.ts, src/backend/middlewares/tokenProxy.ts, src/backend/routes/index.ts, src/backend/routes/modellversjon.ts, src/backend/routes/nais.ts, yarn.lock
Har bumpet versjon av express fra 4 til 5 pluss noen omkringliggende pakker.
Måtte endre noe på middleware som vi hadde kjørende. Typene klaget på at vi returnerte responser, noe som vi ikke skal gjøre. Den skulle ha returnert `void`, noe den gjør nå. Skal selvfølgelig teste godt i preprod før denne merges. Vær obs på at en del av dette ikke kan testes lokalt siden selve frontenden blir servet av webpack-dev-server i localhost, ikke express-serveren som server frontenden i preprod og prod.
Her er migreringsguiden jeg har fulgt: https://expressjs.com/en/guide/migrating-5.html
Er ikke veldig rutta i express, men tror jeg fikk med meg alt som skulle gjøres. Det funker lokalt i hvert fall uten feil i konsollet. …
=> Bump express fra 4 til 5

src/frontend/components/Felleskomponenter/Sanity/TekstBlock.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx, src/frontend/typer/sanity/sanity.ts
- Legger til samme typografi og props i tekstblock som brukes i KS.
- Alt i ett.
=> Legger til samme typografi og props i tekstblock som brukes i KS

src/frontend/components/Felleskomponenter/Arbeidsperiode/ArbeidsperiodeModal.tsx, src/frontend/components/Felleskomponenter/Arbeidsperiode/useArbeidsperiodeSkjema.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeModal.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/useBarnetrygdperiodeSkjema.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/UtbetalingerModal.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/useUtbetalingerSkjema.tsx, src/frontend/utils/mappingTilKontrakt/andreForelder.ts, src/frontend/utils/mappingTilKontrakt/barn.ts, src/frontend/utils/mappingTilKontrakt/eøsBarnetrygdsperiode.ts, src/frontend/utils/mappingTilKontrakt/omsorgsperson.ts, src/frontend/utils/perioder.ts
Favro: [NAV-18711](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18711)
– Dette er en oppfølging av en tidligere oppgave (https://github.com/navikt/familie-ba-soknad/pull/1550), der `MånedÅrVelger`-komponenten ble introdusert og tatt i bruk flere steder. Nå tas `MånedÅrVelger` også i bruk i barnetrygdsperiode.
- Alt i ett.
- Jeg har allerede testet endringene i preprod og generering av PDF.
=> Legger til månedsvelger i barnetrygdsperiode

src/frontend/components/Felleskomponenter/VedleggOppsummering/vedleggOppsummering.domene.ts, src/frontend/components/SøknadsSteg/Dokumentasjon/Dokumentasjon.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg2.tsx, src/frontend/hooks/useSendInnSkjema.tsx, src/frontend/typer/sanity/tekstInnhold.ts, src/frontend/utils/mappingTilKontrakt/dokumentasjon.ts, src/frontend/utils/mappingTilKontrakt/søknad.ts, src/frontend/utils/slåSammen.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24814
Samme oppgave er også gjort i KS: https://github.com/navikt/familie-ks-soknad/pull/910
- Fikser hardkodet "og" tekst i slåSammen funksjonen ved å bytte til Sanity tekst
- Alt i ett.
Nå viser dette "and" istedenfor "og" på engelsk
=> Fikser hardkodet og" tekst

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnet/AndreForelderOppsummering.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25208
Samme oppgave gjøres i KS: https://github.com/navikt/familie-ks-soknad/pull/914
- Endrer wrapper rundt svar om at bruker ikke kan gi opplysninger om den andre forelderen.
- Alt i ett.
=> Fiks accessibility feil i oppsummering

src/frontend/utils/mappingTilKontrakt/søknad.ts
Stopper map() fra å bruker på `svalbardOppholdPerioder` dersom den er undefined som resultat av gammel søknad som sendes inn gjennom ny kode.
=> Fikser undefined svalbardOppholdPerioder som resultat av gammel søknad

Dockerfile, package.json
Logges som error i loki, som gir falske alerts.
Løsning hentet fra: https://github.com/navikt/familie-ba-minside-frontend/pull/135
=> Ignorer deprecationwarning
