src/Miljø.ts
Oppdatere til riktig `loginservice`-link når man kjører i dev
=> fikse loginservice link

package.json, src/App.less, src/App.tsx, src/Søknad.tsx, src/assets/VeilederSnakkeboble.tsx, src/components/Felleskomponenter/SystemetLaster/SystemetLaster.tsx, src/components/Felleskomponenter/SystemetLaster/systemet-laster.less, src/components/Forside/Forside.tsx, src/context/AppContext.ts, src/index.less, yarn.lock
* Legge til navn ved snakkeboble på forsiden
* Legge til navn i bekreftelsesboksen nederst på forsiden
* Innlastingsside som vises imens man venter på at dataen skal bli hentet
=> Vise frem navn på søker

src/components/SøknadsSteg/1-Søknadstype/Søknadstype.tsx, src/context/AppContext.ts
* Legg til søknadsfelt interface
* Utvid søknadsobjektet til å bruke søknadsfelt
* Send søknadsobjekt til api når søknadstype endres
=> Feature/kontrakt søknad

src/Søknad.tsx, src/context/AppContext.ts
* Lagt inn slik at man fjerner ressurs fra liste før man kaster exception
* Lagt til logikk for boolske uttrykk slik at riktig komponenter vises
=> bugfix: fikse laster og feiler bug

src/Søknad.tsx, src/context/AppContext.ts, src/context/axios.ts, src/utils/autentisering.ts
* Flyttet verifiserAtBrukerErAutentisert slik at man bruker AxiosRequest direkte
* Fikset at man ikke thrower exception men heller logger feil
=> bugfix: bruk axios-request direkte for å unngå timeout

src/components/SøknadsSteg/1-Søknadstype/Søknadstype.tsx, src/components/SøknadsSteg/2-VelgBarn/Barnekort/Barnekort.tsx, src/components/SøknadsSteg/2-VelgBarn/VelgBarn.tsx, src/components/SøknadsSteg/3-Oppsummering/Oppsummering.tsx, src/utils/visning.tsx
- Legge til keys på lister
- Flytte Normaltekst inn i div
=> Fjerne warnings i konsollen

src/components/SøknadsSteg/2-VelgBarn/Barnekort/Barnekort.less, src/components/SøknadsSteg/2-VelgBarn/Barnekort/Barnekort.tsx, src/components/SøknadsSteg/2-VelgBarn/VelgBarn.tsx, src/components/SøknadsSteg/3-Oppsummering/Oppsummering.tsx, src/components/SøknadsSteg/Steg/Steg.tsx, src/context/AppContext.ts, src/typer/søknad.ts
Endret type på `søker` og `barn` i søknadsobjektet til Søknadsfelt av typen `Søker` og `List<Barn>`
=> Legg til søknadsfelt på søker og barn

src/components/SøknadsSteg/Steg/Steg.less, src/components/SøknadsSteg/Steg/Steg.tsx
=> fiks neste-knapp når den står alene

.dockerignore, Dockerfile, pull_request_template.md
Oppdaterer denne templaten :D 
=> Oppdater PR-template

README.md
Gjøre det enklere for folk å sette opp prosjektet lokalt
Nei
Det er to linjer i readme.md som er endret
Alt i ett tenker jeg
=> (docs) Oppdater info om lokalt oppsett i readme

src/components/SøknadsSteg/3-VelgBarn/VelgBarn.tsx
=> (chore) Endre VelgBarn til å kun ha ett nivå css

package.json, src/index.tsx, yarn.lock
Legger til axe for å lettere utvikle for god UU
nei
Ikke relevant
Alt i ett
=> Legg til react axe for UU-deteksjon

package.json
Flytter dependencies sammen med dev-deps nederst i package json fila. 
nei
Ingen endringer, ingenting å teste
Alt i ett
=> Flytt dependencies sammen med dev-deps i package

src/frontend/public/index.html, src/webpack/webpack.common.config.js
Ikke hardkode /public i template, gjøre public path tilgjengelig for kode
Nei
Ingenting å teste
Kjør bygg og sjekk at favicon og manifest kan nås?
=> (feat) Putte tilbake PUBLIC_URL som variabel

README.md
La nestemann slippe å nøste opp i alt dette for å få generert pdf
Nei
Kun oppdatering av README
Alt i ett
=> (docs) Legg til oppskrift for pdf-generering i readme

src/webpack/webpack.common.config.js, src/webpack/webpack.development.config.js
At js fetches fra public i prod og preprod
Nei
Webpack-endringer
Alt it ett
Preprod skal rendre nå
=> (fix) Fikser at webpack-generert html leter etter js i public i prod

build_n_deploy/naiserator/naiserator_dev.yaml, package.json, src/backend/server.ts, src/frontend/index.tsx, src/frontend/tsconfig.json, yarn.lock
La til sentry for logging. Måtte endre rootDir i frontend for å få tak i version til package.json. 
alt i ett
=> La til sentry for logging og endret rootDir

src/frontend/index.tsx
Fjerne advarsel om named import fra package.json
=> (fix) Fjern warning om named import fra package.json

src/frontend/components/Felleskomponenter/Informasjonsbolk/Informasjonsbolk.tsx, src/frontend/components/Felleskomponenter/SpråkTekst/SpråkTekst.test.tsx, src/frontend/components/Felleskomponenter/SpråkTekst/SpråkTekst.tsx, src/frontend/components/Forside/BekreftelseOgStartSoknad.tsx, src/frontend/components/Forside/Forside.tsx, src/frontend/components/SøknadsSteg/1-OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/1-OmDeg/Personopplysninger.tsx, src/frontend/components/SøknadsSteg/1-OmDeg/SøkerBorIkkePåAdresse.tsx, src/frontend/components/SøknadsSteg/1-OmDeg/useOmdeg.tsx, src/frontend/components/SøknadsSteg/2-VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/2-VelgBarn/VelgBarn.tsx, src/frontend/components/SøknadsSteg/2-VelgBarn/useVelgBarn.tsx, src/frontend/components/SøknadsSteg/Steg/Navigeringspanel.tsx, src/frontend/components/SøknadsSteg/Steg/Steg.tsx, src/frontend/utils/visning.test.tsx, src/frontend/utils/visning.tsx
Tar i bruk den ny SpråkTekst-komponenten overalt 💫
Flyttet den inn i felleskomponenter-mappen
Alt i ett
=> Ta i bruk ny SpråkTekstKomponent

src/frontend/components/Felleskomponenter/JaNeiSpm/JaNeiSpm.tsx, src/frontend/components/SøknadsSteg/1-OmDeg/OmDeg.tsx
Drar ut JaNeiSpm i en egen komponent
Nei
Ingen endringer, bare flyttet en bolk med kode i egen fil
Alt i ett
=> Dra JaNeiSpm i egen komponent

src/frontend/components/SøknadsSteg/1-OmDeg/OmDeg.tsx
Fikser en liiiiten feil, men feil propsnavn etter refaktorering
=> Oppdater til riktig propsname

package.json, src/frontend/components/Felleskomponenter/KomponentGruppe/KomponentGruppe.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/HvilkeBarnCheckboxGruppe.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useBarnCheckboxFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useJaNeiSpmFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.test.ts, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.ts, yarn.lock
Fikser bugs i erSynlig håndteringen av felter på OmBarnaDine
Nei
Commit for commit, eller alt i ett, opp til deg!
=> Fix/synlige felter statehåndtering

package.json, src/frontend/components/Felleskomponenter/LandDropdown/LandDropdown.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, yarn.lock
bare rydder litt i synlighetslogikk
nei
=> Flytt synlighet logikk inn i komponent

package.json, yarn.lock
Oppgradere postcss-svgo for å fjerne problematisk dependency. Hadde resolution på den, men dependencien er nå helt fjerna.
Nei
Streit oppgradering av dependencies
Alt i ett
=> (chore) Oppgrader depdencencies, fjern resolution om is-svg

src/frontend/components/Forside/BekreftelseOgStartSoknad.tsx, src/frontend/components/Forside/Forside.test.tsx, src/frontend/components/Forside/useBekreftelseOgStartSoknad.tsx, src/frontend/typer/søknad.ts
Lagre at søker har bekreftet i søknadsobjektet.
Nei
Alt i ett
=> Lagre at søker bekrefter i søknadsobjektet

src/frontend/assets/lang/nb.json, src/frontend/components/Felleskomponenter/Banner/Banner.tsx, src/frontend/components/SøknadsSteg/Steg/Steg.tsx
Legger til banner i headeren
Nei
Alt i ett 
=> legg til banner på søknad

package.json, src/frontend/components/Forside/Forside.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.ts, src/frontend/components/SøknadsSteg/OmBarnetUtfyllende/OmBarnetUtfyllende.test.tsx, src/frontend/components/SøknadsSteg/OmBarnetUtfyllende/OmBarnetUtfyllende.tsx, src/frontend/components/SøknadsSteg/OmBarnetUtfyllende/useOmBarnetUtfyllende.tsx, src/frontend/components/SøknadsSteg/Steg/Navigeringspanel.tsx, src/frontend/components/SøknadsSteg/Steg/Steg.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/useLeggTilBarn.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.tsx, src/frontend/context/AppContext.test.tsx, src/frontend/context/AppContext.ts, src/frontend/routing/Routes.test.tsx, src/frontend/routing/RoutesContext.tsx, src/frontend/typer/person.ts, src/frontend/typer/søknad.ts, src/frontend/utils/person.ts
Nullstiller søknad ved avbryt, og rydder i interfaces til Barn
Nei
Alt i ett
=> Fix/nullstill søknad

src/frontend/components/SøknadsSteg/OmDeg/Personopplysninger.test.tsx, src/frontend/typer/person.ts, src/frontend/typer/søknad.ts, src/frontend/utils/person.test.ts, src/frontend/utils/person.ts
Vise poststed som nå kommer med i respons fra backend
Bostedskommune er byttet ut med Poststed i adresseobjekt
Testene eksisterer allerede, kun endret til å bruke poststed
Alt i ett
Før:
Etter:
=> (feat) Vis poststed i frontend med korrekt små og store bokstaver

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx
Legger til manglende melding om asyl og adopsjon på Om Barna 
Nei
Alt i ett
=> Legg til alerts på adopsjon og asyl

src/frontend/components/Felleskomponenter/SøkerMåBrukePDF.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.tsx
Gjenbruk komponent som viser pdf-skjema lenke
Nei
Ingenting nytt egentlig
Alt i ett
=> Samle pdf+info i en komponent og gjenbruk

src/frontend/assets/lang/nb.json, src/frontend/components/SøknadsSteg/OmBarnetUtfyllende/OmBarnetUtfyllende.test.tsx, src/frontend/components/SøknadsSteg/OmBarnetUtfyllende/OmBarnetUtfyllende.tsx, src/frontend/routing/Routes.test.tsx, src/frontend/routing/RoutesContext.tsx
Refaktorer logikk rundt routes og om barnet
nai
=> Refaktorer om barnet-routes logikk

src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/useSendInnSkjema.tsx, src/frontend/typer/søknad.ts
Legge til funksjon for å sende inn søknad
Nei
Fokusert på å generere PDF. Burde sikkert hatt en test men nå er det ikke tid.
Alt i ett
=> (feat) Funskjon for å mappe og sende inn skjema ihht ny kontrakt

src/frontend/index.tsx
Fikse at man får cors-feil når man initer Sentry
Eneste grunn til at vi må gjøre dette er at vår self-hosted sentry er hundgammel
Config-endring av sentry
Alt i ett
=> (fix) Fix sentry session envelope cors-feil

src/frontend/assets/lang/nb.json, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.test.ts, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmBarnet/VetIkkeCheckbox.tsx, src/frontend/components/SøknadsSteg/OmBarnet/spørsmål.ts, src/frontend/components/SøknadsSteg/OmBarnet/useDatovelgerFeltMedUkjent.ts, src/frontend/components/SøknadsSteg/OmBarnet/useInputFeltMedUkjent.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/typer/person.ts
Legger til personopplysninger om den andre forelderen (Navn, fnr, fødselsdato)
Nei
Oppdatert tester med mer info bare, men ikke skrevet nye
Alt i ett. Gjerne check ut branch om du har tid, klikk rundt og frem og tilbake. Sjekk at søknadsdata blir riktig.
=> Legger til personopplysninger om den andre forelderen

src/frontend/components/SøknadsSteg/Forside/Forside.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/useLeggTilBarn.tsx, src/frontend/context/AppContext.ts, src/frontend/typer/person.ts, src/frontend/typer/søknad.ts, src/frontend/utils/person.ts
Legge til info om adressesperre fra api
Nei
Ingenting funksjonelt endret enda, kun lagt til nytt felt fra backend
Alt i ett
=> (chore) Legg til felt for adressesperre på personrespons

src/frontend/components/Felleskomponenter/SkjemaFeltInput/SkjemaFeltInput.tsx, src/frontend/components/Felleskomponenter/Steg/Steg.tsx
Skrur av autcomplete på felter 
Ingenting
har bare testet at det funker i browseren, er vel ikke så mye å skrive tester for selv
Alt i ett
=> Skru av autocomplete på felter

src/frontend/components/Felleskomponenter/LandDropdown/LandDropdown.tsx, src/frontend/components/SøknadsSteg/OmDeg/Personopplysninger.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx
Bruk språkcontext for å hente ut valgt språk istedet for intl
Alt i ett
=> Bruk valgtSpråkContext i stedet for intl for å hente ut språk

src/frontend/assets/lang/nb.json, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx
=> Legg til og i språkfil

src/frontend/components/Felleskomponenter/Steg/Navigeringspanel.tsx, src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/Dokumentasjon.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/utils/testing.tsx
Gjøre det mulig å sende inn skjema via navigasjonspanel etter å ha lastet opp dokumentasjon
Nei
Må sette meg inn i hvordan vi kan mocke axios, har ikke tid nå.
Alt i ett
Knapp blir grå og spinner kommer frem når man trykker på send inn
_
=> (feat) Async skjemainnsending via navigasjonspanel

src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx
Enkel fix på en lenke som hadde feil id.
=> Var lenket til feil i kvittering

src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.tsx
=> Legge til at man kan bruke enter for å komme til knapp

.github/workflows/build_n_deploy_prod.yaml
Fiks deploy til dev når merge til master
Nei
=> (hotfix) Legg på basepath variabel i deploy til dev ved merge til master

src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/useLeggTilBarn.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.tsx
=> Legg modal på utsiden av form

build_n_deploy/naiserator/naiserator_prod.yaml
=> Oppdater prod-url til nyeste

src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx
Fikser autocomplete i legg til barn
nei
=> Fiks autocomplete off

src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx
Fikse at alder og borMedSøker ikke var satt på manuelt registrerte barn
Nei
Tid
Alt i ett
=> (fix) Fikse usatte verdier på nye barn

package.json, src/backend/escape.ts, src/backend/server.ts, yarn.lock
Sanitere input i mellomtjener før det sendes videre til soknad-api
Har også oppdatert `ws` for å fikse https://www.npmjs.com/advisories/1748
Nei
Tredjepartsmodul for sanitering
Alt i ett
=> (feat) Legg til sanitering av søknadsobjekt

src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx
Send inn verdi for lest-og-forstått til pdfgen
Nei
Bare et nytt felt på innsendt objekt
Alt i ett
=> (feat) Send inn 'lest og forstått' bekreftelse

pull_request_template.md, src/frontend/Miljø.ts
(chore) Lagt til punkt for å endre modellversjon i pr-template
Fikse dialogen for folk som var med på testdugnaden, minne folk på modellversjon i pr-template
Nei
Ingen endringer
Alt i ett
=> (chore) Bump modellversjon for mellomlagring

src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx
Fiks innsending av manuelt lagt  til barn
Nei
Hotfix
Alt i ett
=> (hotfix) Fix mapping av barn med borMedSøker undefined

src/frontend/components/SøknadsSteg/Forside/Forside.tsx
=> Infoboks engelsk

src/frontend/context/AppContext.ts, yarn.lock
Fjerner feilmelding ved oppstart
nei
=> Fjern at systemet feiler ved innloggingsfeil

src/frontend/components/Felleskomponenter/RedirectTilStart/RedirectTilStart.tsx, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/context/AppContext.ts
Unngå å kunne navigere til kvitteringn når kvitteringen ikke er gyldig. feks når man prøver å navigere direkte til kvittering, uten å gå gjennom søknaden.
nei
=> Naviger alltid til forsiden med mindre mna har en gyldig kvitttering

src/frontend/components/Felleskomponenter/VedleggNotis.tsx
=> Fiks høyde på vedlegg-ikon

src/frontend/Miljø.ts, src/frontend/components/SøknadsSteg/OmBarnet/spørsmål.ts
Hadde sneket seg inn et mellomrom i en id, som ødela anchortagging
=> Fiks feil i id

src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx
Setter nullstill til false på feltet som "ødelegger" validering, og gjør at man må trykke på "gå videre"- knappen to ganger.
nei
Alt i ett
=> Fiks felt som ikke validerte riktig

src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/LeggTilBarnModal.tsx
Endre aria-label til lesbar tekst
Nei
Anser det som unødvendig her
Alt i ett
=> (fix) Bruk språktekst for aria-label på modal

src/frontend/components/SøknadsSteg/OmBarnaDine/useBarnCheckboxFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useDatovelgerFeltMedUkjent.ts, src/frontend/components/SøknadsSteg/OmDeg/useDatovelgerFeltMedJaNeiAvhengighet.ts, src/frontend/components/SøknadsSteg/OmDeg/useLanddropdownFeltMedJaNeiAvhengighet.tsx
Fikser slik at feilmeldinger ikke rendres for oppfølgningsfelter som rendres første gang. 
Har testet EN DEL frem og tilbake for å sjekke at alt stemmer. Jeg klarer ikke finne noe feil. Men gjerne ta en dobbeltsjekk. Console.log eller sjekk i oppsummeringen at dato og landfelt er slik man forventer, også når man har navigert tilbake og endret f.eks. 
OBS, ser også at det er en del kode nå som er iiish-likt men ikke helt. Kanskje vi burde vurdere en refaktorering snart for eksempel og lage litt mer felles hooks. Men tok meg ikke bryet til å gjøre det i denne PR'en. 
Alt i ett. Gjerne sjekk ut branch og console.log søknadsobjektet som nevnt over, eller sjekk i …
=> Fix/feilmelding på første render

src/frontend/components/Felleskomponenter/Steg/Steg.tsx
Fikser brekkpunkt for stegindikatoren.
nei
alt i ett
=> Legg til en container for stegindikator

package.json, src/frontend/components/SøknadsSteg/Forside/Forside.tsx, yarn.lock
Fikse at ikoner forsvinner når man zoomer inn i språkvelger
Nei
Endringene er i familie-dokument
Alt i ett
=> (fix) Språkvelger zoom-fiks

src/frontend/components/SøknadsSteg/Forside/FortsettPåSøknad.tsx, src/frontend/components/SøknadsSteg/Forside/useBekreftelseOgStartSoknad.tsx
Vi en bekreftelsesmodal før man starter søknaden på nytt
nei
Alt i ett
=> Start på nytt-modal

package.json, src/frontend/tsconfig.json
Kjør typescript før commit
Nei
=> Kjør typescript check på commit

src/frontend/components/SøknadsSteg/OmBarnet/VetIkkeCheckbox.tsx
Validerer checkbox ved første render, slik at man ikke må trykke gå videre to ganger.
=> Valider checkbox ved render

package.json, src/backend/dekorator.ts, src/backend/feature-toggles.ts, src/backend/server.ts, src/frontend/assets/lang/nb.json, src/frontend/components/Disabled/DisabledApp.tsx, src/frontend/disabled.tsx, src/frontend/public/disabled.html, src/webpack/webpack.common.config.ts, src/webpack/webpack.development.config.ts, yarn.lock
Støtte for å vise vedlikeholdsside via unleash
Nei. Utvikling av dette er irr fordi hot reload ikke funker, burde være en enkel fiks i webpack config.
Tidsklemme og mangler testsuite for node-backend.
Alt i ett
=> (feat) Støtte for unleash-toggles med cluster-strategy

src/webpack/webpack.common.config.ts, src/webpack/webpack.development.config.ts
=> Fiks broken hot-reload

src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/components/SøknadsSteg/VelgBarn/useVelgBarn.tsx, src/frontend/utils/amplitude.ts
Sette antall valgte barn som prop i amplitude slik at vi kan segmentere på det
Nei
Trenger ikke skrive tester for 3.parts kode
Alt i ett
=> (feat) Sett antall valgte barn i amplitude

src/webpack/webpack.common.config.ts, src/webpack/webpack.development.config.ts, src/webpack/webpack.production.config.ts
Fix at man redirectes til start når man navigerer direkte til en tilfeldig path
Også forenkling ved å fjerne unødvendige plugins etter bytte vekk fra webpack express middleware
Nei
Bare webpack config endringer
Alt i ett
=> (hotfix) Fix at man redirectes til start fra random paths

src/backend/feature-toggles.ts, src/frontend/components/Disabled/DisabledApp.tsx, src/frontend/disabled.tsx
Fikse at appen man får når vi skrur på killswitch har språkstøtte, og ser lik ut som den vanlige appen.
Nei
Bare bøffet litt basic stuff fra main app
Alt i ett
=> (feat) Språkstøtte i disabledApp.

src/backend/feature-toggles.ts
=> (hotfix) Legg tilbake feature-toggle check

src/frontend/components/SøknadsSteg/Forside/Forside.tsx
Riktig tekst om pdf-søknad for utvida barnetrygd
Nei
Hastverk og minimal endring
=> (fix) Vis gammel tekst om utvidet-søknad frem til vi går live

src/frontend/Miljø.ts
=> Bump modellversjon

src/webpack/webpack.common.config.ts
Hotfix i webpack. Manglet basepath for rendring av disabled.
=> Hotfix for en feil i webpack som gjorde at disabled rendres feil

src/backend/feature-toggles.ts, src/frontend/components/Disabled/DisabledApp.tsx
Legger til toggle for å skru av utvidet og ordinaer hver for seg
Alt i ett
=> Legger til toggle for å skru av utvidet og ordinaer hver for seg

src/frontend/assets/lang/nb.json, src/frontend/components/SøknadsSteg/Utvidet-DinLivssituasjon/DinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/Utvidet-DinLivssituasjon/useDinLivssituasjon.tsx
Legger til oppfølgningspørsmål dersom svarer ja på skilt-enke-spørsmålet.
Alt i ett
=> Feature/skilt oppfølgning

src/frontend/components/SøknadsSteg/Utvidet-DinLivssituasjon/DinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/Utvidet-DinLivssituasjon/useDinLivssituasjon.tsx
La til Ja/nei spm om man har hatt tidligere samboere
Alt i ett
=> La til spørsmål om man har hatt tidligere samboer

build_n_deploy/naiserator/naiserator_prod.yaml
Legger til ingress for utvidet
=> Legg til ingress for utvidet

src/frontend/context/AppContext.ts
Sender med søknadstype i innlogging requesten, slik at vi kan i backend logge metrics for innlogging separert på søknadstype
=> Send søknadstype som param i innlogging req

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json
=> Legg til feilmelding for barn ikke valgt i Om Barna

.gitignore, package.json, yarn.lock
=> Bump nav-frontend-skjema

package.json, yarn.lock
=> bump frontend-skjema-style

src/frontend/components/Felleskomponenter/Dropdowns/StyledDropdown.tsx, src/frontend/components/Felleskomponenter/Dropdowns/ÅrsakDropdown.tsx
=> Fix empty dropdown

src/frontend/components/SøknadsSteg/Utvidet-DinLivssituasjon/useDinLivssituasjon.tsx
Fikser denne feilen: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=Tea-6144
=> Nullstill fødselsdato til samboer dersom man svarer Nei på smaboer

src/frontend/components/SøknadsSteg/Dokumentasjon/useSendInnSkjema.tsx
=> Fikser bug på vi bor sammen nå-label

src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/HvilkeBarnCheckboxGruppe.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useBarnCheckboxFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.tsx, src/frontend/components/SøknadsSteg/VelgBarn/useVelgBarn.tsx, src/frontend/context/AppContext.ts, src/frontend/typer/person.ts, src/frontend/utils/testing.tsx
Lar vær å mellomlagre ved innsending.
Gjort ved å lagre current route i AppContext (ikke optimalt kanskje, men enklest), og legge på en sjekk om bruker er på Dokumentasjon steg i useEffect som kjører mellomlagring
=> ikke mellomlagre hvis på steg Dokumentasjon

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx
=> Fiks manglende import

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
Kjøre `yarn typecheck` i github pipeline før deploy slik at vi ikke deployer knekt react
Nei
Alt i ett
=> (feat) Kjør typecheck i pipeline for å unngå brekte deploys

src/frontend/Theme.ts, src/frontend/components/Felleskomponenter/InnholdContainer/InnholdContainer.tsx, src/frontend/index.less, src/frontend/public/index.html
plaserer footer nederst på siden, istede for fixed på bunn av viewport
mobil før:
mobil etter:
før
etter
=> plaserer footer nederst

src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx
Før var det et slikt advarsel symbol nederst. Endret til informasjons symbol
=> endrer ! ikon til i ikon

src/frontend/components/Felleskomponenter/Datovelger/Datovelger.test.tsx, src/frontend/context/RoutesContext.tsx
Fikse at man får feilmelding når man navigerer direkte til om-barnet/barn-1
Nei
Alt i ett
=> (fix) RoutesFinder default og fikset test

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx
Lagt til spørsmålet "bor du på denne adressen" i oppsummeringen.
Trenger ikke test for dette på oppsummering, og har test for språkid
=> (feat) Legge til spm oppsummering

src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx
Vise konto-info på kvittering etter at eøs-status på søknad er nullstilt
Nei
Anses unødvendig
Alt i ett
=> (fix) Egen state for varEøs på kvittering

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/hooks/useSendInnSkjema.tsx, src/frontend/typer/søknad.ts, src/frontend/utils/typeguards.ts, src/shared-utils/modellversjon.ts
Vise riktig verdi for registrert bostedsadresse i pdf
Nei
Anser endringer dekket av typesikkerhet
Alt i ett
=> (feat) Barnetrygd kontrakt v5

docker-compose.yml, dockerstuff/mottak/gitdiff
Gjøre det mulig å sende inn søknader med nyeste frontend i docker-compose stack
Nei
Ingen kodeendringer
Alt i ett
=> (chore) Oppdater docker-compose stack etter kontraktendring

src/frontend/components/Felleskomponenter/LeggTilKnapp/LeggTilKnapp.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/TidligereSamboere.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/OmDeg/spørsmål.ts, src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx, src/frontend/typer/person.ts, src/frontend/typer/skjema.ts, src/frontend/typer/søknad.ts, src/frontend/utils/testing.tsx
Gjenbruke "legg-til"-knapp fra samboer på utlandsopphold
Nei
Knappen har ingen funksjon å teste enda
Alt i ett
=> (feat) Knapp for å legge til utlandsopphold

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/Felleskomponenter/Datovelger/Datovelger.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/spørsmål.ts, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/useUtenlandsoppholdSkjema.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/OmDeg/UtenlandsoppholdModalForSøker.tsx, src/frontend/hooks/useDatovelgerFelt.ts, src/frontend/hooks/useLanddropdownFelt.tsx, src/frontend/typer/skjema.ts, src/frontend/typer/spørsmål.ts, src/frontend/typer/utenlandsopphold.ts, src/frontend/utils/dato.tsx, src/frontend/utils/spørsmål.ts
Lage en modal og et skjema for utenlandsopphold
`samletSpørsmålSpråkTekstId` som jeg måtte endre type på er ikke i bruk
Work in progress
Alt i ett
=> (feat) Modal for å legge til utenlandsopphold for søker

src/frontend/components/Felleskomponenter/Datovelger/Datovelger.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/useUtenlandsoppholdSkjema.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/OmDeg/UtenlandsoppholdModalForSøker.tsx, src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/hooks/useLanddropdownFelt.tsx, src/frontend/typer/person.ts, src/frontend/typer/skjema.ts, src/frontend/typer/søknad.ts, src/frontend/typer/utenlandsopphold.ts, src/frontend/utils/dato.tsx
Legger til utenlandsperioden på søknaden og fikser en bug der den tryner når man går ut av modalen. 
Flyttet også litt på noen typer pga. cycle imports
=> Diverse fixes utenlandsopphold

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/spørsmål.ts
Endrer spørsmål i Om Barna, se screenshot
nei
Alt i ett
FØR:
ETTER:
=> Endre spm tekst på Om Barna vært sammenhengende i Norge

src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/OmDeg/UtenlandsperiodeSøkerOppsummering.tsx, src/frontend/utils/eøs.test.ts, src/frontend/utils/eøs.ts
Vise EØS-notis hvis ett av utenlandsoppholdene til søker var i EØS-land
Nei
Alt i ett
=> Feat/eøs notis utenlandsopphold søker

src/frontend/hooks/useSendInnSkjema.tsx
Send utenlandsperioder til backend
nai
alt i ett
=> Send utenlandsperioder til backend

src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnet/OmBarnetOppsummering.tsx, src/frontend/utils/utenlandsopphold.tsx
Ikke vis spørsmål om barn planlegger å bo i Norge dersom det har flyttet ut fra Norge permanent
På sikt tenker jeg vi kan lage en avhengighet til det nye feltet som kommer "registrerteUtenlandsperioder", da kan vi sjekke om vi har svart på den før vi faktisk viser dette spørsmålet. 
Alt i ett
=> Ikke vis planlegger å bo i Norge dersom barn er permanent utflyttet

src/frontend/hooks/useSendInnSkjema.tsx, src/frontend/typer/søknad.ts
Send utenlandperioder i ny kontraktformat
=> Utenlandsperioder i ny kontrakt format

src/frontend/components/Felleskomponenter/LeggTilKnapp/LeggTilKnapp.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx
Rød border på knapp dersom feilmelding pga manglende periode
Fiks hyperlenking ved feilmelding
nei
=> Legg på border på leggtilknapp ved feil

src/frontend/components/Felleskomponenter/JaNeiSpm/JaNeiSpm.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.test.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx
Flytter en melding ut av utenlandsmodal
Refaktorerte litt i samme slengen, slik at styling blir likt på tvers av sidene, og mindre kode. 
=> Flytt melding ut av modal og refaktorer litt

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx
Fikset litt bugs i styling som hang igjen fra da et spørsmål var fjernet i Om Barna.
Endrer også slik at infomelding om utenlandperioder alltid vises
=> Fiks styling og melding om utenlandsperioder

src/shared-utils/modellversjon.ts
=> (hotfix) Bump modellversjon

src/frontend/utils/barn.ts
Var en bug i Om Barna, der vi sjekker om barnet er fosterbarn, og nullstiller noen felt deretter. Men sjekken med fosterbarn var feil.
nei
=> Fiks bug med nullstilling når man går videre fra Om Barna

src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/SamboerSkjema.tsx, src/frontend/components/SøknadsSteg/OmBarnet/AndreForelder.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx
Fiks rare avstander til checkbox, se screenshots
FØR:
ETTER:
FØR:
ETTER:
FØR:
ETTER:
=> Fiks rare avstander til checkbox

src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx
Tomt postnummer gir egen feilmelding
Fjernet en feilmelding om lenger enn 10 pga vi allerede har en generell feilmelding om gyldig format. Tror uansett at dette skal endres egentlig, med at vi bare kan ha postnr på 4 tall
=> Egen feilmelding for tomt postnummer

src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx
Legg til begrensing på når institusjonsopphold starter
=> Legg til begrensing på når institusjonsopphold starter

build_n_deploy/naiserator/naiserator_dev.yaml, build_n_deploy/naiserator/naiserator_prod.yaml
Sørge for at vi alltid kjører på minst to podder
=> (feat) Pod redundans

.github/workflows/build_n_deploy_dev.yaml
=> Legger til workflow-dispatch for dev-deployment

src/shared-utils/modellversjon.ts
=> bumper modellVersjon

package.json, src/scripts/find-missing-text-ids.js
lager skript som leter etter manglende tekstider
=> manglende tekst id'er

src/frontend/components/SøknadsSteg/DinLivssituasjon/Arbeidsperiode.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/DinLivssituasjonOppsummering.tsx
Småfiks av renderingfeil. Gjelder.
Rendret arbeidsland i oppsummering selvom vi ikke har svart på den
Styling feil av arbeidsland-dropdown
FØR: 
ETTER:
=> Småfiks av UI ting

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/SøknadsSteg/EøsSteg/Barn/EøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Søker/EøsForSøker.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Søker/useEøsForSøker.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/EøsBarnOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/EøsSøkerOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummeringsbolk.tsx, src/frontend/context/StegContext.tsx
Legger til oppsummeringsdropdown for eøs-steg på oppsummeringssiden
=> Feature/oppsummering eøs steg

src/frontend/components/Felleskomponenter/Pensjonsmodal/Pensjonsperiode.tsx, src/frontend/components/Felleskomponenter/Pensjonsmodal/språkUtils.ts, src/frontend/components/Felleskomponenter/Pensjonsmodal/usePensjonSkjema.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Søker/EøsForSøker.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Søker/spørsmål.ts, src/frontend/components/SøknadsSteg/EøsSteg/Søker/useEøsForSøker.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/EøsSøkerOppsummering.tsx, src/frontend/typer/person.ts, src/frontend/typer/skjema.ts, src/frontend/typer/søknad.ts, src/shared-utils/modellversjon.ts
Pensjonsperiode i Norge for eøs søker
=> Legger til pensjon for norge på søker

src/frontend/components/Felleskomponenter/Arbeidsperiode/Arbeidsperiode.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/EøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/EøsBarnOppsummering.tsx, src/frontend/typer/barn.ts, src/frontend/typer/skjema.ts, src/frontend/utils/barn.ts, src/frontend/utils/testing.tsx, src/shared-utils/modellversjon.ts
legger til arbeidsperiode for andre forelder på eøs barn-steget
=> Legg til arbeidsperiode på barn eøs

src/frontend/assets/lang/nb.json, src/frontend/components/Felleskomponenter/Pensjonsmodal/usePensjonSkjema.tsx
=> nullstilles så riktig feilmelding dukker opp og tekstendring

package.json, yarn.lock
=> Fjern request-pakke

src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmBarnet/spørsmål.ts, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/typer/barn.ts, src/frontend/typer/skjema.ts
Kun spørsmålet om man mottar eller har mottatt
Featuretogglet mellom dette nye spørsmålet og hvilket land på gammel
Setter ikke data 
Nytt spørsmål:
=> la til nytt spm om barn og featuretoggle

README.md
Oppdatere readme med hva som skal til for å få stacken til å kjøre
=> Oppdater readme

docker-compose.yml, src/frontend/typer/kontrakt/v7.ts, src/frontend/utils/mappingTilKontrakt/barnV7.ts, src/frontend/utils/mappingTilKontrakt/søknadV7.ts
Legger til harEøsSteg og antallEøsSteg i objektet som sendes til backend til bruk i dokgen
=> Feat/antall eøs steg i kontrakt

src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmBarnet/spørsmål.ts, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnet/OmBarnetOppsummering.tsx, src/frontend/typer/barn.ts, src/frontend/typer/skjema.ts, src/frontend/utils/barn.ts, src/shared-utils/modellversjon.ts
Legger til nytt spørsmål på V7 om man har en pågående søknad, og hvilket lang denne søknaden evt er fra. 
På om barnet
Oppsummering
=> Feat/pågående søknad nytt spm

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/SøknadsSteg/EøsSteg/Barn/EøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/spørsmål.ts, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsBarnOppsummering.tsx, src/frontend/hooks/useInputFelt.tsx, src/frontend/typer/barn.ts, src/frontend/typer/skjema.ts, src/frontend/utils/barn.ts, src/shared-utils/modellversjon.ts
Legger til at man må spesifisere slektsforholdet om man velger annen relasjon. 
Vises kun når man har valgt annen_relasjon
Feilmeldinger
=> Legger til at man må spesifisere annen relasjon

src/frontend/utils/barn.ts, src/shared-utils/modellversjon.ts
Fikser prod feil. https://sentry.gc.nav.no/organizations/nav/issues/46977/?project=71&query=is%3Aunresolved
=> fikser feil modellversjon i prod

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/SøknadsSteg/EøsSteg/Barn/EøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/spørsmål.ts, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsAndreForelderOppsummering.tsx, src/frontend/typer/barn.ts, src/frontend/typer/kontrakt/v7.ts, src/frontend/typer/skjema.ts, src/frontend/utils/barn.ts, src/frontend/utils/mappingTilKontrakt/andreForelderV7.ts, src/frontend/utils/testing.tsx, src/shared-utils/modellversjon.ts
Legger til adresse til den andre forelderen
=> Feat/andre forelder eøs adresse

src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx
Ikke vise adresse til andre forelder dersom søker er enke
=> Skjul adresse til andre forelder dersom enke

src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsBarnOppsummering.tsx, src/frontend/typer/barn.ts, src/frontend/typer/kontrakt/v7.ts, src/frontend/utils/mappingTilKontrakt/omsorgspersonV7.ts, src/frontend/utils/testing.tsx, src/shared-utils/modellversjon.ts
Endret navn for omsorgsperson til å fjerne prefixen. 
Fra oppsummering
=> omsorgsperson navneendring

src/frontend/context/EøsContext.ts
Fjerne at EØS_VEDLEGG legges til om man har v7.
V7 søknad
V6 søknad
=> Trenger ikke eøs vedlegg i v7

src/frontend/assets/lang/en.json, src/frontend/assets/lang/nb.json, src/frontend/assets/lang/nn.json, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Søker/useEøsForSøker.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/utils/adresse.tsx
Sjekk om adressen er over 100 tegn. Usikker på om jeg burde samle logikken til en fellesfunksjon eller om det er rotere å ha den logikken et annet sted? 🤔 
=> ny feilmelding når adresser over 100 tegn

src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsperiodeOppsummering.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx
Fjerner de siste vedleggnotisene som fortsatt var synlig dersom toggelen er på.
=> Fjern vedleggsnotiser dersom eøstoggle er på

src/frontend/components/SøknadsSteg/DinLivssituasjon/useDinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/typer/barn.ts, src/frontend/typer/common.ts, src/frontend/utils/barn.ts, src/frontend/utils/søker.ts
Dersom man går tilbake på forrige steg og endrer slik at brukeren ikke trenger å fylle inn eøs skjema likevel, ønsker vi å nullstille alle eøs-feltene slik at dette ikke blir med videre til backend
=> Feat/nullstill eøsfelter

src/frontend/components/Felleskomponenter/Datovelger/Datovelger.tsx
Fikser sånn at tab fungerer med datepicker i safari i modalene
=> Fiks bug der tab ikke fungerer med datepicker i modaler i safari

src/frontend/components/Felleskomponenter/Arbeidsperiode/ArbeidsperiodeModal.tsx, src/frontend/components/Felleskomponenter/Arbeidsperiode/ArbeidsperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/Arbeidsperiode/arbeidsperiodeSpråkUtils.ts, src/frontend/components/Felleskomponenter/Arbeidsperiode/spørsmål.ts, src/frontend/components/Felleskomponenter/Arbeidsperiode/useArbeidsperiodeSkjema.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeModal.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/barnetrygdperiodeSpråkUtils.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/spørsmål.ts, src/frontend/components/Felleskomponenter/Barnetrygdperiode/useBarnetrygdperiodeSkjema.tsx, src/frontend/components/Felleskomponenter/Pensjonsmodal/Pensjonsmodal.tsx, src/frontend/components/Felleskomponenter/Pensjonsmodal/PensjonsperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/Pensjonsmodal/språkUtils.ts, src/frontend/components/Felleskomponenter/Pensjonsmodal/spørsmål.ts, src/frontend/components/Felleskomponenter/Pensjonsmodal/usePensjonSkjema.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/UtbetalingerModal.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/UtbetalingsperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/spørsmål.ts, src/frontend/components/Felleskomponenter/UtbetalingerModal/useUtbetalingerSkjema.tsx, src/frontend/utils/mappingTilKontrakt/andreUtbetalingsperioder.ts, src/frontend/utils/mappingTilKontrakt/arbeidsperioder.ts, src/frontend/utils/mappingTilKontrakt/eøsBarnetrygdsperiode.ts, src/frontend/utils/mappingTilKontrakt/pensjonsperioder.ts, src/frontend/utils/perioder.ts
Refaktorer tilbakeITid til periodenErAvsluttet
=> Refaktorer tilbakeITid til periodenErAvsluttet

docker-compose.yml, src/backend/routes/api.ts, src/frontend/components/Felleskomponenter/Arbeidsperiode/ArbeidsperiodeModal.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeModal.tsx, src/frontend/components/Felleskomponenter/Dropdowns/LandDropdown.test.tsx, src/frontend/components/Felleskomponenter/Dropdowns/LandDropdown.tsx, src/frontend/components/Felleskomponenter/Pensjonsmodal/Pensjonsmodal.tsx, src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/Felleskomponenter/UtenlandsoppholdModal/UtenlandsoppholdModal.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/DinLivssituasjon.tsx, src/frontend/components/SøknadsSteg/EøsSteg/IdNummer.tsx, src/frontend/components/SøknadsSteg/OmBarnet/AndreForelder.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/utils/mappingTilKontrakt/andreUtbetalingsperioder.ts, src/frontend/utils/mappingTilKontrakt/utenlandsperiode.ts, src/shared-utils/modellversjon.ts
Fikser sentry feil TypeError cannot use in operator to search for 'melding'
Fikser nyeste gitcommit i dokgen for å kjøre opp stack uten dokgen lokalt
Fikser at Norge vises i landlisten i andre utbetalinger, men ingen andre land dropdown
Fikser feil der checkbox tekst var feil og ble sendt til dokgen
Idnummer kan være ukjent for andre forelder og barn alltid
Fjern stegindikator fra kvitteringssiden
=> Småfiks av bugs

src/frontend/assets/lang/en.json, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsBarnOppsummering.tsx, src/frontend/utils/barn.ts, src/frontend/utils/mappingTilKontrakt/barnV7.ts, src/frontend/utils/mappingTilKontrakt/hjelpefunksjoner.ts, src/frontend/utils/språk.ts
=> Sjekke om svar eksisterer først

src/frontend/components/Felleskomponenter/Dropdowns/LandDropdown.test.tsx, src/frontend/components/Felleskomponenter/Dropdowns/LandDropdown.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/DinLivssituasjon.test.tsx, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.test.tsx, src/frontend/context/AppContext.ts, src/frontend/context/EøsContext.ts, src/frontend/utils/testing.tsx
Viser feilside dersom kodeverk-kall feiler. Dette fordi søknaden er avhengig av kodeverk. 
=> Vis feilside dersom kodeverk går ned

src/webpack/webpack.common.config.ts
=> Fiks babel-plugin

src/frontend/components/Felleskomponenter/Pensjonsmodal/PensjonsperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/UtbetalingsperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/UtbetalingerModal/språkUtils.ts, src/frontend/components/SøknadsSteg/EøsSteg/Barn/EøsForBarn.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/Omsorgsperson.tsx, src/frontend/components/SøknadsSteg/EøsSteg/Barn/spørsmål.ts, src/frontend/components/SøknadsSteg/EøsSteg/Barn/useEøsForBarn.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsBarnOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsOmsorgspersonOppsummering.tsx, src/frontend/typer/kontrakt/v7.ts, src/frontend/typer/omsorgsperson.ts, src/frontend/typer/skjema.ts, src/frontend/utils/mappingTilKontrakt/omsorgspersonV7.ts, src/frontend/utils/testing.tsx
=> legger til andre utbetalinger for omsorgsperson

src/frontend/components/SøknadsSteg/OmBarnet/AndreForelder.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.test.tsx, src/frontend/components/SøknadsSteg/OmBarnet/useOmBarnet.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.test.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/Eøs/EøsOmsorgspersonOppsummering.tsx, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata1.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata4.ts, src/frontend/typer/kontrakt/v8.ts, src/frontend/typer/skjema.ts, src/frontend/utils/barn.ts, src/frontend/utils/mappingTilKontrakt/andreForelderV8.ts, src/frontend/utils/mappingTilKontrakt/barnV8.ts, src/frontend/utils/testing.tsx, src/frontend/utils/typeguards.ts
Rydder opp sist av navnUkjent/kanIkkeGiOpplysninger navnekrøll
Fikser en bug i rekkefølge på oppsummering
Fikser noen todos som var lagt inn i koden
=> Diverse småfiks

package.json, yarn.lock
=> Bump @navikt/fnrvalidator slik at den validerer data fra Test-Norge

package.json, src/frontend/components/Felleskomponenter/LeggTilKnapp/LeggTilKnapp.tsx, src/frontend/components/Felleskomponenter/SkjemaModal/SkjemaModal.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/Filopplaster.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.tsx, src/frontend/index.tsx, yarn.lock
Tar inn det nye designsystemet og css. Fikser det som ble knekt. Prep for at man kan fase ut alle de gamle pakkene.
=> Legg inn pakken og css til nytt designsystem og fiks det som knekker

package.json, yarn.lock
Force versjon av got og oppgrader nodemon
=> Oppgrader nodemon og force versjon av got

package.json, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/useFilopplaster.tsx, yarn.lock
Unngå å bruke file-type til filopplastning. Vi får det vi trenger fra fil.type, så vi trenger ikke file-type pakken, og siden den er vulnerable, og oppgraderingen ikke er bakover kompatibel bare fjernet jeg den.
=> Fjern file-type pakke og refaktorer useFilopplaster

package.json, src/backend/middlewares/jwt-interceptor.ts, yarn.lock
=> oppdatere openid-client

package.json, yarn.lock
Manuell oppdatering av html-webpack-plugin.
=> Oppdatere html-webpack-plugin

src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx
Har bare endret to feilmeldingtekstider som var feil
=> Endre til riktig tekst

Dockerfile, src/backend/server.ts, src/csp.ts
Legger på csp-header for sikkerhet
Har kopiert den fra familie-ks-søknad
=> Legg på csp-header for sikkerhet

.github/dependabot.yml
Legger til dependabot for github-actions
=> Legg til dependabot for github-actions

src/frontend/context/pdl.ts
Endre endepunkt for personopplysning til GET i stedet for POST
=> Endre endepunkt for personopplysning til get

package.json, src/frontend/components/Felleskomponenter/BlokkerTilbakeKnappModal/BlokkerTilbakeKnappModal.tsx, src/frontend/components/Felleskomponenter/ModalContent.tsx, src/frontend/components/Felleskomponenter/SkjemaModal/SkjemaModal.tsx, src/frontend/components/Felleskomponenter/Steg/ModellVersjonModal.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/Filopplaster.tsx, src/frontend/components/SøknadsSteg/Forside/FortsettPåSøknad.tsx, src/frontend/index.tsx, yarn.lock
* Bruker Modal fra `navikt/ds-react` fremfor `nav-frontend-modal`
* Fjernet avhengighet til `nav-frontend-modal` og `nav-frontend-modal-style`
=> Tatt ibruk Modal fra ds-react alle steder vi har modal i løsningen

.dockerignore, var/mottatte_soknader/.gitignore
Hang igjen en mappe som ikke var ryddet opp etter at vi fjernet dockerstuff-logikken
=> Rydd opp en mappe som hørte til tidligere dockerstuff-opplegget

package.json, src/frontend/components/SøknadsSteg/Dokumentasjon/Dokumentasjon.tsx, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, yarn.lock
Fjern resterende bruk av dayjs
=> Fjern bruk av dayjs

Dockerfile, README.md, package.json, yarn.lock
=> Bump til node 18

src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx
Fjern dynamisk logik på om barna slik som er gjort på ks-søknaden, da denne koden er ganske komplisert og forvirrende
=> Fjern logikk for dynamiske spørsmål på om barna

package.json, src/frontend/components/Felleskomponenter/JaNeiSpm/JaNeiSpm.tsx, src/frontend/components/Felleskomponenter/expandableContent/ExpandableInfo.tsx, src/frontend/components/SøknadsSteg/EøsSteg/IdNummer.tsx, src/frontend/hooks/useInputFelt.tsx, src/frontend/hooks/useInputFeltMedUkjent.tsx, src/frontend/hooks/useJaNeiSpmFelt.tsx, src/frontend/hooks/useLanddropdownFeltMedJaNeiAvhengighet.tsx, yarn.lock
=> Fjern bruken av guid fra nav-frontend-js-utils

Dockerfile
Bytter til å bruke node fra Nav fra ghcr i stedet for dockerhub.
Må downgrade til 16 for å ta i bruk denne. Tenker likevel at det er lurt å gjøre: https://github.com/navikt/baseimages
=> Bytte til å hente node-image fra ghcr i stedet for dockerhub

package.json, src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/context/Steg.test.tsx, src/frontend/context/StegContext.tsx, yarn.lock
Bytter til å bruke Stepper fra Aksel i stedet for stegindikator fra det gamle designsystemet
FØR:
NÅ:
=> Bytt til stegindikator/Stepper fra Aksel

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
Endrer fra docker/build-push-action til nais/docker-build-push for å bygge og deploye til gcp
=> Bruk nais/docker-build-push for bygging og deploy

.github/workflows/build_n_deploy_prod.yaml
Legger til `deploy-preprod` i `needs` for produksjon i bygg-og-deploy filen for prod
=> Legger til deploy-preprod i needs

package.json, src/frontend/components/Felleskomponenter/LeggTilKnapp/LeggTilKnapp.tsx, src/frontend/components/Felleskomponenter/PeriodeOppsummering/PeriodeOppsummering.tsx, src/frontend/components/Felleskomponenter/VedleggNotis.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/SamboerOpplysninger.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/Filopplaster.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/filopplaster/OpplastedeFiler.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/FjernBarnKnapp.tsx, yarn.lock
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-14951
Oppgraderer ikoner til aksel-icons som en del av større oppgradering. 
Nei
Bytter bare ut ikoner
Samme 🤷‍♂️
Se kommentarer
=> Oppgrader fra ds-icons til aksel-icons

.github/workflows/deploy-unleash-api-token.yaml, build_n_deploy/naiserator/unleash/unleash-apitoken-dev.yaml, build_n_deploy/naiserator/unleash/unleash-apitoken-prod.yaml
Config for tilgang til unleash next
=> Nav 14468 unleash token workflow

.github/workflows/build_n_deploy_dev.yaml
=> Ikke bygg docker image i PR hvis dependabot

src/backend/middlewares/proxy.ts
Requesten mot familie-dokument stoppet opp etter innføring av PR https://github.com/navikt/familie-ba-soknad/pull/1003
Denne PR'en fikser bugen.
=> Sett next() utenfor if sånn at requesten ikke stopper opp

build_n_deploy/naiserator/naiserator_dev.yaml, build_n_deploy/naiserator/naiserator_prod.yaml
Fikset nais-filene slik at de får lov til å deploye neste uke
https://nav-it.slack.com/archives/CJN0STWB0/p1702477815839139
=> Fjern team:familie i naiseratorfil

.husky/pre-commit, package.json, yarn.lock
=> Bump husky 4 => 8

.github/workflows/build_n_deploy_dev.yaml
Hele steget for bygg ble droppet dersom det er dependabot, dette ønsker vi ikke. Legger derfor til bygg yarn for dependabot
=> Bygg yarn for dependabot

src/backend/server.ts, src/backend/utils/unleash.ts, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.test.tsx, src/frontend/components/SøknadsSteg/Forside/BekreftelseOgStartSoknad.tsx, src/frontend/components/SøknadsSteg/Forside/Forside.tsx, src/frontend/components/SøknadsSteg/Forside/useBekreftelseOgStartSoknad.tsx, src/frontend/context/AppContext.test.tsx, src/frontend/context/AppContext.ts, src/frontend/typer/søknad.ts, src/frontend/utils/testing.tsx
Favro: [NAV-18565](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18565)
Spørsmål om hvorvidt man søker utvidet barnetrygd eller ikke er lagt til på forsiden. Svaret styrer hva som blir satt på feltet `søknadstype` på `Søknad`-objektet.
All ny funksjonalitet er lagt bak den nye feature-toggelen `KOMBINER_SOKNADER`.
Testet ok med toggel av og på i preprod. Toggel av = alt skal fungere likt som før. Toggel på = nytt spørsmål på forsiden, men ellers fungere likt som før.
Alt i ett.
=> Styrer søknadstype gjennom nytt spørsmål på forsiden.

src/csp.ts
Lagt til Sanity url i "connect-src" i csp.ts
=> Lagt til Sanity url i connect-src i csp.ts

.github/workflows/build_n_deploy_dev.yaml, .github/workflows/build_n_deploy_prod.yaml
I [denne](https://github.com/navikt/familie-ba-soknad/pull/1187) PRen ble image fjernet fra outputs-lista til bygg-steget og deploy feiler derfor til både preprod og prod fordi den ikke finner bildet. Legger tilbake image i outputs-listen.
Testet og verifisert at dette bygger og deployer til preprod.
Nei
Gir ikke mening
Samme
Nei
=> Bugfix: feilende deploy pga image ikke eksponeres fra bygg-steget

README.md, src/frontend/Theme.ts, src/frontend/components/Felleskomponenter/Barnetrygdperiode/Barnetrygdperiode.tsx, src/frontend/components/Felleskomponenter/Barnetrygdperiode/BarnetrygdperiodeOppsummering.tsx, src/frontend/components/Felleskomponenter/Informasjonsbolk/Informasjonsbolk.tsx, src/frontend/components/Felleskomponenter/PeriodeOppsummering/PeriodeOppsummering.tsx, src/frontend/components/Felleskomponenter/SkjemaFeiloppsummering/SkjemaFeiloppsummering.tsx, src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/LastOppVedlegg.tsx, src/frontend/components/SøknadsSteg/OmBarnet/OmBarnetHeader.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/typer/common.ts
https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-18702
Vi har byttet heading nivåer for å gjøre søknaden mer semantisk riktig og enklere å finne frem med tilgjengelighetsverktøy.
Vi har kun gjort endringer i heading nivåer, ingen funksjonelle endringer har blitt gjort.
Alt i ett.
Det visuelle har ikke endret seg.
=> Feat/fikse heading nivåer

package.json, src/csp.ts, src/frontend/public/index.html, src/jest-setup.ts, yarn.lock
Fjerner gamle polyfills som nå har blitt en sikkerhetstrussel.
Ikke noe spesielt jeg er bekymret for 
Jeg har kjørt testene som var der og sjekket at alt kjørte OK.
Første commit er den faktiske sikkerhetstrusselen. Andre commit er en lignende pakke som ikke er maintainet lengre og ble kun brukt til testene våre. Usikker på om det er noe sikkerhetstrusler der (sannsynligvis ikke), men fjernet den likevel. Testene kjører grønt.
=> Fjern polyfill

src/frontend/components/SøknadsSteg/OmBarnet/OmBarnet.tsx, src/frontend/components/SøknadsSteg/OmBarnet/innholdTyper.ts, src/frontend/typer/sanity/tekstInnhold.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21863
- Legger til guide for "Om barnet" steget.
- Ikke nødvendig
- Sjekk at guide for steget "Om barnet" er riktig.
=> Legger til guide for "Om barnet" steget

src/shared-utils/Miljø.ts
- Bytter datasett fra ba-test til ba-production
=> Bytter datasett fra ba-test til ba-production

src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx
Endrer velg barn tekst til å være uavhengig av utvidet
=> Endrer velg barn tekst til å være uavhengig av utvidet

src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.test.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx
Favro (to oppgaver):
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21866
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-21867
- Fjerner warnings etter avklaring med Miriam og Anna.
- Fjerner test for sjekking av alert etter som denne ikke lengre eksisterer.
Det eneste som endres er at warnings er borte.
=> Fjerner unødvendige warnings

src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/Felleskomponenter/Steg/useFormProgressSteg.tsx
- Bytter til bruk av template literal formProgressStegOppsummeringTekst
- Legger til bedre kommentarer for alleRouteEnumMedlemmerGjennomgås
=> Legger til små forbedringer i kodekvalitet

src/backend/middlewares/erklaering-interceptor.test.ts, src/backend/middlewares/erklaering-interceptor.ts, src/backend/middlewares/escape.ts, src/frontend/components/SøknadsSteg/Dokumentasjon/Dokumentasjon.tsx, src/frontend/components/SøknadsSteg/OmDeg/innholdTyper.ts, src/frontend/context/AppContext.ts, src/frontend/hooks/useSendInnSkjema.tsx, src/frontend/hooks/useSendInnSkjemaTest/konverteringTilISøknadKontrakt.test.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata1.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata2.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata3.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata4.ts, src/frontend/hooks/useSendInnSkjemaTest/test-data/testdata5.ts, src/frontend/hooks/useSendInnSkjemaTest/useSendInnSkjema.test.tsx, src/frontend/typer/kontrakt/v8.ts, src/frontend/typer/sanity/sanity.ts, src/frontend/utils/mappingTilKontrakt/andreForelderV8.ts, src/frontend/utils/mappingTilKontrakt/andreUtbetalingsperioder.ts, src/frontend/utils/mappingTilKontrakt/arbeidsperioder.ts, src/frontend/utils/mappingTilKontrakt/barnV8.ts, src/frontend/utils/mappingTilKontrakt/eøsBarnetrygdsperiode.ts, src/frontend/utils/mappingTilKontrakt/idNummer.ts, src/frontend/utils/mappingTilKontrakt/omsorgspersonV8.ts, src/frontend/utils/mappingTilKontrakt/pensjonsperioder.ts, src/frontend/utils/mappingTilKontrakt/søknadV8.ts, src/frontend/utils/testing.tsx, src/frontend/utils/typeguards.ts
Reverts navikt/familie-ba-soknad#1340
=> Revert "Tar i bruk V9 av endepunkt for innsending av søknad"

src/frontend/components/Kontoinformasjon/Kontoinformasjon.tsx, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/components/SøknadsSteg/Kvittering/innholdTyper.ts
- Flytter tekster for kvittering over til Sanity.
- Endret tekstinnhold (som nå ligger i Sanity).
- Legger til warning-alert som vises dersom bruker ikke har sendt alle relevante vedlegg.
- Endrer whitespace mellom komponenter.
- Ikke nødvendig
- Alt i ett
=> Forbedring av kvitteringssiden

build_n_deploy/naiserator/naiserator_dev.yaml, src/shared-utils/Miljø.ts
Favro: [NAV-23001](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23001)
Vi ønsker ikke at søknaden skal ligge helt åpent tilgjengelig på internett i dev. Fjerner derfor ekstern-ingress og legger til intern- og ansatt -ingress.
=> NAV-23001: Erstatter ekstern ingress med intern og ansatt

build_n_deploy/naiserator/naiserator_dev.yaml, build_n_deploy/naiserator/naiserator_prod.yaml, package.json, src/csp.ts, src/frontend/index.tsx, src/frontend/utils/grafanaFaro.ts, yarn.lock
Eksponere telemetri i tjenesten slik at vi kan overvåke hva som skjer. Benytter NAIS auto-instrumentation, samt bruker Grafana Faro for innsamling. I vårt tilfelle: metrikker og tracing-data.
https://docs.nais.io/observability/how-to/auto-instrumentation/
https://docs.nais.io/observability/frontend/
La også til prometheus-endepunkt i dev. Ser ikke noe grunn til at den ikke skal være der.
Ikke forretningslogikk
NAIS sin doc, som er lenket over.
N/A
=> Legg til auto-instrumentation + grafana faro

src/frontend/components/Felleskomponenter/JaNeiSpm/JaNeiSpmForSanity.tsx, src/frontend/utils/amplitude.ts
Fjerner unødvendig logging av spørsmål og svar til amplitude
Løser [https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23102](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23102)
=> Fjerner logging av svar til amplitude

package.json, src/frontend/utils/amplitude.ts, yarn.lock
=> Chore: bytt fra amplitude-js til @amplitude/analytics-browser

package.json, src/webpack/webpack.development.config.ts, yarn.lock
Ny PR siden det ble git historikk-kluss med den forrige: https://github.com/navikt/familie-ba-soknad/pull/1352
Det eneste jeg er usikker på er hvorfor `webpack-dev-server` lå i `dependencies` i stedet for `devDependencies`. Jeg fant ingen god grunn, så jeg flyttet den.
Ikke relevant
Alt i ett
=> Bump webpack dev server

src/frontend/components/SøknadsSteg/OmBarnaDine/HvilkeBarnCheckboxGruppe.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/innholdTyper.ts, src/frontend/components/SøknadsSteg/OmBarnaDine/useBarnCheckboxFelt.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/useOmBarnaDine.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/utils.ts
Favro: [NAV-23514](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23514)
- Legger til Sanity tekster i "Om barna" steget.
- Ikke nødvendig
- Alt i ett
=> Legger til Sanity tekster i "Om barna" steget

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/VelgBarnOppsummering.tsx, src/frontend/components/SøknadsSteg/VelgBarn/Barnekort/Barnekort.tsx, src/frontend/components/SøknadsSteg/VelgBarn/VelgBarn.test.tsx, src/frontend/components/SøknadsSteg/VelgBarn/innholdTyper.ts, src/frontend/utils/språk.ts
Favro: [NAV-23743](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23743)
- Legger til sanity tekster i VelgBarnOppsummering.
- Alt i ett.
- Ingen visuelle endringer.
=> Legger til sanity tekster i VelgBarnOppsummering

package.json, src/frontend/App.tsx, src/frontend/Søknad.tsx, src/frontend/components/Felleskomponenter/AppLenke/AppLenke.tsx, src/frontend/components/Felleskomponenter/BlokkerTilbakeKnappModal/BlokkerTilbakeKnappModal.test.tsx, src/frontend/components/Felleskomponenter/RedirectTilStart/RedirectTilStart.tsx, src/frontend/components/Felleskomponenter/Steg/ScrollHandler.tsx, src/frontend/components/Felleskomponenter/Steg/Steg.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/NåværendeSamboer.test.tsx, src/frontend/components/SøknadsSteg/DinLivssituasjon/TidligereSamboere.test.tsx, src/frontend/components/SøknadsSteg/Dokumentasjon/Dokumentasjon.test.tsx, src/frontend/components/SøknadsSteg/Forside/useBekreftelseOgStartSoknad.tsx, src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDine.tsx, src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/components/SøknadsSteg/VelgBarn/LeggTilBarn/NyttBarnKort.test.tsx, src/frontend/context/AppNavigationContext.tsx, src/frontend/context/Steg.test.tsx, src/frontend/context/StegContext.tsx, src/frontend/utils/testing.tsx, src/jest-setup.ts, yarn.lock
Den samme oppdateringen som på [BA-sak](https://github.com/navikt/familie-ba-sak-frontend/pull/3497).
Her er guiden jeg brukte for å oppgradere: https://reactrouter.com/upgrading/v6
Denne trenger mest av alt å testes grundig av noen andre enn meg. Den som ser på saken må kjøre opp branchen lokalt og teste der.
Ikke relevant. Men jeg har fikset testene som var 🙌 
Commit for commit
Det skal ikke være noen visuelle endringer 😊
=> Oppdater react router dom v6 til react-router v7

src/frontend/components/SøknadsSteg/Oppsummering/Oppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnaOppsummering.tsx
Favro: [NAV-23953](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23953)
- Legger til Sanity tekster i OmBarnaOppsummering.
- Legger til Sanity tekst for tittel i `Oppsummering.tsx` og endrer rekkefølge på små deler av koden for å gjøre den likere ks-søknad sin struktur.
- Alt i ett.
=> Legger til Sanity tekster i OmBarnaOppsummering

src/frontend/components/Disabled/DisabledApp.tsx, src/frontend/typer/sanity/sanity.ts, src/frontend/typer/sanity/tekstInnhold.ts, src/frontend/utils/sanity.ts
Favro: [NAV-24011](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24011)
- Legger til Sanity tekster i DisabledApp.
- Alt i ett.
=> Legger til Sanity tekster i DisabledApp

src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnet/OmBarnetOppsummering.tsx
Favro: [NAV-23992](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-23992)
- Legger til Sanity tekster i OmBarnetOppsummering.
- Alt i ett.
=> Legger til Sanity tekster i OmBarnetOppsummering

package.json, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx, src/frontend/components/SøknadsSteg/VelgBarn/useVelgBarn.tsx, src/frontend/hooks/useUxSignals.ts, src/frontend/index.tsx, src/frontend/utils/amplitude.ts, yarn.lock
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-24165
Sjekker samtykke pluss bytter til å bruke dekoratøren sin Amplitude-instans i steden for vår egen.
Ingenting jeg er spesielt bekymret for.
Ikke relevant, men jeg har kjørt testene, alt kjører grønt.
Alt i ett
=> Legger på sjekk av samtykke før vi logger til Amplitude

.nais/app-dev.yaml, .nais/app-prod.yaml
Endringen ble revertet utilsiktet. Tilsvarende oppsett som i ks-søknad.
=> Sett base-path manuelt i nais-fil

eslint.config.mjs, package.json
Bygg og commit her i søknadene er ganske treigt. Fikser noen av synderne, men kan sannsynligvis optimalisere mer fremover.
Dette burde spare oss rundt 1 minutt 15 sekunder per gang vi bygger, og rundt 1 minutt per commit (der vi kun kjører linting).
Ingen bekymringer. Så lenge dette bygget kjører grønt på github actions burde det være plankekjøring.
Ikke relevant
Commit for commit
Ingen endringer
=> Gjør testene og linting raskere

package.json, src/backend/middlewares/tokenProxy.ts, src/frontend/typer/feature-toggles.ts, yarn.lock
Favro: NAV-18733
Legger inn kode for å ta i bruk navikt/oasis for validering og utveksling av obo token
Testet i preprd, og ligger bak toggle
=> Legger inn kode for å ta i bruk navikt/oasis for validering og utveksling av obo token

src/csp.ts, src/frontend/components/SøknadsSteg/Kvittering/Kvittering.tsx
Favro: [NAV-25057](https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25057)
Erstatter eksisterende survey med ny, og sørger for at den kun vises på kvitteringssiden for utvidet barnetrygd søknader.
=> NAV-25057: Legger til ny survey og sørger for at den kun vises for utvidet

package.json, yarn.lock
Disse typene ble ikke inkludert i hovedpakkene slik jeg hadde trodd. Legger de derfor tilbake.
Ingenting å fremheve
Ikke relevant
Alt i ett?
=> Legger tilbake typer jeg tidligere hadde fjernet

package.json, yarn.lock
Jeg skulle fikse eslint-webpack-plugin på samme måte som på saksbehandlingsløsningene, men fant ut at den samme pluginen er installert men ikke blir brukt til noe. Fjerner'n dermed.
Ingen bekymringer
Ikke relevant
Alt i ett
=> Fjerner ubrukt dependency eslint-webpack-plugin

.github/workflows/build-pr.yaml, .github/workflows/deploy-unleash-api-token.yaml
Vi mangler permissions på noen av workflowene våre. I fix. Tar minste tilganger enn så lenge, så kan vi bumpe det hvis vi noen gang trenger det.
Ingenting å fremheve
Ikke relevant
Alt i ett
Ingen endringer
=> Legger på permissions på workflow-filer

mocks/testdata/sanity/sider/omBarna.ts, src/frontend/components/SøknadsSteg/OmBarnaDine/innholdTyper.ts
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25796
- Legger til Sanity tekster slik at de kan brukes for denne oppgaven: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25796
- Tekster som ble lagt til:
- `boddPaaSvalbard`: https://familie-baks-soknad.sanity.studio/ba-production/structure/steg;omBarna;sporsmal;582faf57-5d24-441e-9fb6-065b3991873f
- `hvemBoddPaaSvalbard`: https://familie-baks-soknad.sanity.studio/ba-production/structure/steg;omBarna;sporsmal;96c510f1-5f94-4e8e-a832-b9dc3dddc17c
- Alt i ett.
- Ingen visuelle endringer.
=> Legger til tekster for spm om svalbard i "Om barna" steget

src/frontend/components/SøknadsSteg/OmDeg/useOmdeg.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx
- Fikser feil: https://sentry.gc.nav.no/organizations/nav/issues/615468/?project=71&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0
=> Legger toggle rundt bor på svalbard

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDineSkjema.tsx
Favro: https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25796
Legger spørsmålene om Svalbardtillegg for Om barna bak toggle.
Ingenting å fremheve
Ikke relevant
Alt i ett
=> Legg på toggle

src/frontend/components/SøknadsSteg/OmBarnaDine/OmBarnaDineSkjema.tsx, src/frontend/components/SøknadsSteg/OmBarnet/Oppfølgningsspørsmål.tsx, src/frontend/components/SøknadsSteg/OmDeg/OmDeg.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnaOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmBarnet/OmBarnetOppsummering.tsx, src/frontend/components/SøknadsSteg/Oppsummering/OppsummeringSteg/OmDegOppsummering.tsx, src/frontend/hooks/useSendInnSkjema.tsx, src/frontend/typer/feature-toggles.ts
Toggle ble lagt til som del av disse oppgavene:
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25793
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25796
- https://favro.com/organization/98c34fb974ce445eac854de0/1844bbac3b6605eacc8f5543?card=NAV-25776
- Fjerner toggle: SPM_OM_SVALBARD
- Alt i ett.
=> Fjerner toggle: SPM_OM_SVALBARD
